### ISSUE TITLE
Support multiple source/classes directories per version

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#178]
Currently, we support only one source/classes directory per version, such that we have to create different versions, e.g., for misuses in production and test code. I would like to merge these into one. My suggestion is to allow multiple source/classes directories. Maybe without copying files into intermediate directories anymore... have to think this through.

**Comment by M8is** [comment]
I just encountered another problem:
Currently, we derive the path to misuse source and class files using the paths given in the version. This will not work anymore, since we have no way to map the relative misuse path to the specific source/classes path. We will probably have to specify the misuse paths relative to the repository root instead. 

On another note, we can omit copying the misuse files as well, can't we?

**Comment by salsolatragus** [comment]
No, we cannot omit copying them, because in E1 we provide only the misuse file as a target (as opposed to all files from the project). Therefore, we need to separate this file.

Regarding the copying you have a point though... we could either specify the files relative to the project root, or we could assume that the file can only exist in one of the source/classes roots (after all, if two files with the same relative path and the same name exist in different roots, they will collide on class loading). In the latter case, we'd have to check all roots if they contain a respective file and fail of there is none or more than one... what do you think?

**Comment by salsolatragus** [comment]
Copy directory into a zip file in Python: https://stackoverflow.com/questions/1855095/how-to-create-a-zip-archive-of-a-directory

**Comment by salsolatragus** [comment]
TODO:

* [] Release the CLI
* [] Migrate all detectors
* [] Double check dataset
