### ISSUE TITLE
Duplicated entry on meta snippets

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#190]
This might already be resolved after we finish the refactoring, but just to make sure:

Currently, uploading metadata fails when there is more than one snippet, because the meta_snippet table has its primary key on (project,version,misuse). I think the best solution is to include the line number in the key, because multiple snippets from the same file will always have a different line number.

**Comment by joschli** [comment]
In the new model we don't have a difference between FindingsSnippets and MetadataSnippets, because finding snippets could get multiple on project, version,misuse already I did not set a unique key. The question is if I set (project, version,misuse,line) as a unique key does that also work with FindingSnippets or will it be necessary to make two types of Snippets?
