### ISSUE TITLE
Document usage of Docker volumes for checkouts and findings

### ISSUE THREAD

**Issue by M8is** [stg-tud/MUBench#305]
When I run any checkouts in docker, the checkouts are not persistent. Here's an example log:
[run_20180216_102136.log](https://github.com/stg-tud/MUBench/files/1730923/run_20180216_102136.log).
This happens for all repository types. On a second run, we even find the repository, as the checkout is skipped then: [run_20180216_102405.log](https://github.com/stg-tud/MUBench/files/1730932/run_20180216_102405.log). But I can't find the checkout anywhere in my MuBench folder.
Also, it works if I call the pipeline directly, so I assume this is a problem in the docker script.

**Comment by salsolatragus** [comment]
It's not a bug, but a feature ;)

Due to the problems with file locks on Windows, I decided to store checkouts in a Docker volume instead of on the host file system. This is why the checkout doesn't leave a trace in your host folder, but the pipeline still finds it. This has some disadvantages for development, because browsing the checkout is less convenient. However, it is a huge usability improvement for anyone else...

I agree, however, that this needs to be documented and that there should also be instructions on how to access the checkouts now. Short version is you can mount the volume into a shell like this:

    docker run --rm -it -v mubench-checkouts:/mubench/checkouts -v mubench-findings:/mubench/findings svamann/mubench-pipeline /bin/bash

**Comment by M8is** [comment]
That sounds pretty cool. :) Thanks for the quick info.
