### ISSUE TITLE
Update run modified date on new findings

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#319]
I would like the run modification date to show the time that the latest findings for the run was inserted. Should be possible using Eloquents "touches" property: https://laravel.com/docs/5.0/eloquent#touching-parent-timestamps

**Comment by joschli** [comment]
I just tried to implement this with the touches attribute. The problem is a lot of our tests introduce for example a Misuse with a random run_id (because we dont need a run in the test). These tests fail if we use the touches attribute because it tries to update the run that doesnt exist. 
I can fix this by creating dummy runs in all the failing tests or we insert the timestamp our self whenever we insert a finding. What would you prefer?

**Comment by salsolatragus** [comment]
To implement our own handling, we would still have to put a special handling for a non-existent run into the production code, right? I would prefer not having to handle test-only scenarios explicitly in the production code. Consequently, we would have to "fix" our test setup to add runs where necessary... can we introduce some kind of test factory (or factories) that all tests can use to create test data with "correct" setup, such that future changes like this need to happen in one place only?
