### ISSUE TITLE
Anonymous mode

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#324]
I want the review site to have an anonymous mode (configurable in the settings) where all reviewer names are displayed as `reviewer-<id>` instead of their true names. Furthermore, in this mode, I want to be able to hide some of the detector's names. For this, I imagine some configuration like this:

    'blind_mode' = [
        'enabled' => true,
        'detector_blind_names' => ['Jadet' => 'Foo']
    ]

**Comment by joschli** [comment]
We talked about using detector ids in the urls in blind mode so the urls don't stop working when enabling/disabling blind mode. What do you think about just translating the blinded detector names to the real detector names independent from the blind mode instead of switching to the ids in the blind mode? This results in the same behaviour but we don't have to use ids in the urls.

**Comment by salsolatragus** [comment]
Functionally, I don't see any real difference between these two alternatives. I'm still in favor of using the Id, because it allows the controller to stay oblivious to the blinding... what's you argument for using the names (besides having consistent URLs between anonymous and public mode, which I don't really count, because no one ever sees both in parallel)?
