### ISSUE TITLE
handle broken uploads more gracefully

### ISSUE THREAD

**Issue by Delors** [stg-tud/MUBench#33]
if the pipeline fails and need to be reexecuted, the pipeline will definitively fail due to database table issues

**Comment by salsolatragus** [comment]
Uploading additional findings fails due to SQL error "Table already exists 'status_1'". Seems like the creation logic does not recognize properly that the table already exists.

**Comment by joschli** [comment]
Did you empty the table before uploading the findings ? our current logic for testing if a table exists cannot handle empty tables.

**Comment by salsolatragus** [comment]
I think this happened to me this morning even with a non-empty table, but in any case, we should treat the empty-table scenario. We currently query the `first()` row to fetch the table columns. This fails if the table does not exist and if it is empty. How about we query for `limit(1)` instead, which results 1 or 0 rows if the table exists and fails otherwise. Then, to determine the columns of an empty table, we could insert a line and delete it again... doesn't sound too cool, but do you see another way, @joschli ?
