### ISSUE TITLE
Provide a ./mubench debug command

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/MUBench#355]
The command should prepare project data, such that it is available from the host system and output the command-line arguments required to run a detector on this data from the IDE.

**Comment by salsolatragus** [comment]
Try something like and remote debugging:

    mvn package -DskipTests=true
   docker run -it -v /my/path/detector.jar:/mubench/detectors/detector/latest/detector.jar ./pipeline run ex1 detector --only aclang --java-options suspend=n

**Comment by M8is** [comment]
It works! Using a script with

```
#!/bin/bash

SCRIPT_DIR=$(dirname "$([[ "$0" = /* ]] && echo "$0" || echo "$PWD/${0#./}")")
MUBENCH_ROOT=$SCRIPT_DIR

PIPELINE_CHECKOUTS_VOLUME=mubench-checkouts
PIPELINE_FINDINGS_VOLUME=mubench-findings

DOCKER_IMAGE_USERNAME=svamann
DOCKER_IMAGE_TAG=latest
DOCKER_IMAGE=${DOCKER_IMAGE_USERNAME}/mubench-pipeline:${DOCKER_IMAGE_TAG}

docker run --rm -v "$MUBENCH_ROOT":/mubench -v ${PIPELINE_CHECKOUTS_VOLUME}:/mubench/checkouts -v ${PIPELINE_FINDINGS_VOLUME}:/mubench/findings -v $1:$2 -p 5005:5005 ${DOCKER_IMAGE} python ./mubench.pipeline/benchmark.py ${*:3} --java-options agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005
```

allows us to do something like `mubench-debug /mydetector /mubench/detectors/latest/mydetector run ex1 --only aclang`. Mounting files is possible but we would have to mount the directory first so that docker doesn't create the mounted file as a directory. Its probably easier to just mount the directory where the jar is output.
This starts and suspends the detector on each run. Then, open up the respective sources in your IDE. For IntelliJ IDEA, you can add a new build configuration using the `Remote` template. Shouldn't be hard on other IDEs as well.
Set a breakpoint, attach the debugger, and you should be good to go.

Obviously, the script won't need the setup anymore once our CLI rework is on master. Then we can just use `./mubench debug <path to my files> <where my files should be mounted> <any pipeline arguments>`. For detector-specific debugging we could probably shorten that to `./mubench debug <path-to-jar> <any pipeline arguments>`.

**Comment by salsolatragus** [comment]
Sounds awesome. I'll give this a try next week and then we can integrate it once I've closed the CLI rework. Thanks for figuring this out!
