### ISSUE TITLE
Review decision not shown in review site if you're not logged in

### ISSUE THREAD

**Issue by ervina** [stg-tud/MUBench#425]

**Comment by salsolatragus** [comment]
This is because there is no decision yet, only your review, which is shown only to you in order to avoid influencing other reviewers. By default, MUBench expects two agreeing reviews or a disagreement resolution in order to publicly display a decision. You can change this to 1 in [the review site config](https://github.com/stg-tud/MUBench/blob/master/mubench.reviewsite/settings.default.php#L26). Note that this invalidates the reviewer-agreement numbers (Kappa scores).
