### ISSUE TITLE
Consider code snippets size for chunking requests

### ISSUE THREAD

**Issue by mreif** [stg-tud/MUBench#51]
I tried two upload 200 findings with large Java source files. Experiencing internal server errors, I inspected the code of the publish_finding task. I recognized that the slicing of findings did not work in my case. Every finding had exactly one file which was not found in the loop of publish_findings_task.py => _slice_by_max_files_per_post.

**Comment by salsolatragus** [comment]
If I get your setting correctly, then the problem is that the snippets are not send as files, but as strings, and are, thus, not considered for the slicing. We currently slice only because PHP doesn't accept sending more than 20 files in one request (by the default setting).

Can you elaborate more on the internal server error that you faced? Is it that the total request size gets too large for the server? In that case we should add an additional slicing criterion, I guess...

**Comment by mreif** [comment]
Sorry, I didn't notice that commented the issue... Whatever, I assumed that the snippets are sent as files. Since they are not, your assumption is correct, the total request size got too large and as result, everything crashed. I think it would make sense to either send source snippets as files (this might be too much work) or add an additional slicing criterion that also considers other parts of the request.

**Comment by salsolatragus** [comment]
Don't worry, I had plenty of other things to do ;)

Since our usual scenario is to extract only methods (as opposed to full files, as in your case), sending files will requires to create new files from the strings we have in memory, just for sending. I'd prefer to avoid that. However, it should be possible to determine the size of the request sent to the server from the size of the data (including the snippets) and to use that as an additional slicing criterium. We'll look into it. Thanks for clarifying!
