### ISSUE TITLE
Closure project is compiled without line numbers

### ISSUE THREAD

**Issue by govindsinghnegi** [stg-tud/MUBench#80]
Findbugs with Closure project does not have line numbers

**Comment by salsolatragus** [comment]
It's an `ant` compile, so line numbers in Bytecode are disabled by default. We can enable them by setting the `debug="on"` attribute on the `javac` tag.

**Comment by salsolatragus** [comment]
This is not as easy as it seemed. Adding the `debug="on"` flag causes compilation to fail. I'm not sure yet why. We'll have to investigate this more deeply.

@govindsinghnegi since this is not a blocker for your work and I don't have the time to dive deeper into it in the next two weeks, I'll have to defer fixing this. I'm sorry.

**Comment by salsolatragus** [comment]
@govindsinghnegi This is fixed with 2e7eeba446de35d916d3435577482436fc90bd5c. Closure now compiles with line numbers. Also, we implemented a fix for the problems you had with compilation on windows (#97), which means you should be able to compile on your machine as well. Can you please pull the most recent version of MUBench, try this out, and let me know how it went?

**Comment by govindsinghnegi** [comment]
@salsolatragus I tried with the latest MUBench code and can confirm that this bug along with bug #97 is fixed.

**Comment by salsolatragus** [comment]
Thanks for the confirmation.
